# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './/RapidView/RapidAlphaWindow.ui'
#
# Created: Fri Sep 14 09:31:14 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RapidAlphaWindow(object):
    def setupUi(self, RapidAlphaWindow):
        RapidAlphaWindow.setObjectName(_fromUtf8("RapidAlphaWindow"))
        RapidAlphaWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/alpha.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RapidAlphaWindow.setWindowIcon(icon)
        RapidAlphaWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        RapidAlphaWindow.setDocumentMode(False)
        RapidAlphaWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        RapidAlphaWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(RapidAlphaWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PlotTabs = QtGui.QTabWidget(self.centralwidget)
        self.PlotTabs.setObjectName(_fromUtf8("PlotTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.AlphaPlot = MatplotlibWidget(self.tab)
        self.AlphaPlot.setObjectName(_fromUtf8("AlphaPlot"))
        self.verticalLayout_2.addWidget(self.AlphaPlot)
        self.PlotTabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.CepstrumPlot = MatplotlibWidget(self.tab_2)
        self.CepstrumPlot.setObjectName(_fromUtf8("CepstrumPlot"))
        self.verticalLayout.addWidget(self.CepstrumPlot)
        self.PlotTabs.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.PlotTabs)
        RapidAlphaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RapidAlphaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        RapidAlphaWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RapidAlphaWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RapidAlphaWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(RapidAlphaWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        RapidAlphaWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtGui.QAction(RapidAlphaWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExport_Graph = QtGui.QAction(RapidAlphaWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/export_graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Graph.setIcon(icon2)
        self.actionExport_Graph.setObjectName(_fromUtf8("actionExport_Graph"))
        self.actionExport_Data = QtGui.QAction(RapidAlphaWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/export_data.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Data.setIcon(icon3)
        self.actionExport_Data.setObjectName(_fromUtf8("actionExport_Data"))
        self.actionLoad_Measurement = QtGui.QAction(RapidAlphaWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Measurement.setIcon(icon4)
        self.actionLoad_Measurement.setObjectName(_fromUtf8("actionLoad_Measurement"))
        self.actionExit = QtGui.QAction(RapidAlphaWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPreferences = QtGui.QAction(RapidAlphaWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon5)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionStart_Measurement = QtGui.QAction(RapidAlphaWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Measurement.setIcon(icon6)
        self.actionStart_Measurement.setObjectName(_fromUtf8("actionStart_Measurement"))
        self.actionSave_Preferences = QtGui.QAction(RapidAlphaWindow)
        self.actionSave_Preferences.setObjectName(_fromUtf8("actionSave_Preferences"))
        self.actionLoad_Preferences = QtGui.QAction(RapidAlphaWindow)
        self.actionLoad_Preferences.setObjectName(_fromUtf8("actionLoad_Preferences"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Graph)
        self.menuFile.addAction(self.actionExport_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Measurement)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionSave_Preferences)
        self.menuFile.addAction(self.actionLoad_Preferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionLoad_Measurement)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionExport_Graph)
        self.toolBar.addAction(self.actionExport_Data)
        self.toolBar.addAction(self.actionStart_Measurement)
        self.toolBar.addAction(self.actionPreferences)

        self.retranslateUi(RapidAlphaWindow)
        self.PlotTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RapidAlphaWindow)

    def retranslateUi(self, RapidAlphaWindow):
        RapidAlphaWindow.setWindowTitle(QtGui.QApplication.translate("RapidAlphaWindow", "Rapid Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotTabs.setTabText(self.PlotTabs.indexOf(self.tab), QtGui.QApplication.translate("RapidAlphaWindow", "Absorption Coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotTabs.setTabText(self.PlotTabs.indexOf(self.tab_2), QtGui.QApplication.translate("RapidAlphaWindow", "Cepstrum", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("RapidAlphaWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("RapidAlphaWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("RapidAlphaWindow", "Save Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Graph.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Export Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Graph.setToolTip(QtGui.QApplication.translate("RapidAlphaWindow", "Export Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Graph.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Data.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Export Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Data.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Measurement.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Load Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Measurement.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+,", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Measurement.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Start Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Measurement.setShortcut(QtGui.QApplication.translate("RapidAlphaWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Preferences.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Save Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Preferences.setText(QtGui.QApplication.translate("RapidAlphaWindow", "Load Preferences", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
import icons_rc
